# example v1.0.0 8ea6c2298bb7597dce55f9ec922fba0a5257fc54
# --
# Code generated by webrpc-gen@unknown with .. generator. DO NOT EDIT.
#
# webrpc-gen -schema=example.ridl -target=.. -client -server -out=./example.gen.py
from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional, Protocol

WEBRPC_HEADER = "Webrpc"
WEBRPC_HEADER_VALUE = "webrpc@unknown;..@unknown;example@v1.0.0"

WEBRPC_VERSION = "v1"
WEBRPC_SCHEMA_VERSION = "v1.0.0"
WEBRPC_SCHEMA_HASH = "8ea6c2298bb7597dce55f9ec922fba0a5257fc54"



ItemName = str

Quantity = int

class ItemTier(Enum):
    REGULAR = "REGULAR"
    PREMIUM = "PREMIUM"

    @classmethod
    def from_dict(cls, v: Any) -> "ItemTier":
        return cls(v)

@dataclass
class Item:
    id: str
    name: ItemName
    tier: ItemTier
    count: int
    quantity: Quantity
    balance: int
    tags: list[str]
    attributes: dict[str, str]
    class_: str
    createdAt: datetime
    lastUpdate: Optional[datetime] = None
    notes: Optional[list[str]] = None
    labels: Optional[dict[str, str]] = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Item":
        return cls(
            id=data.get("id"),
            name=data.get("name"),
            tier=ItemTier.from_dict(data.get("tier")),
            count=data.get("count"),
            quantity=data.get("quantity"),
            balance=_parse_bigint(data.get("balance")),
            tags=[_e0 for _e0 in (data.get("tags") or [])],
            attributes={ _k0:_v0 for _k0, _v0 in (data.get("attributes") or {}).items() },
            class_=data.get("class"),
            createdAt=_parse_datetime(data.get("createdAt")),
            lastUpdate=None if data.get("lastUpdate") is None else _parse_datetime(data.get("lastUpdate")),
            notes=None if data.get("notes") is None else [_e0 for _e0 in (data.get("notes") or [])],
            labels=None if data.get("labels") is None else { _k0:_v0 for _k0, _v0 in (data.get("labels") or {}).items() },
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": _to_value(self.id),
            "name": _to_value(self.name),
            "tier": _to_value(self.tier),
            "count": _to_value(self.count),
            "quantity": _to_value(self.quantity),
            "balance": _bigint_to_value(self.balance),
            "tags": [_to_value(_e0) for _e0 in (self.tags or [])],
            "attributes": { _to_value(_k0): _to_value(_v0) for _k0, _v0 in (self.attributes or {}).items() },
            "class": _to_value(self.class_),
            "createdAt": _to_value(self.createdAt),
            "lastUpdate": None if self.lastUpdate is None else _to_value(self.lastUpdate),
            "notes": None if self.notes is None else [_to_value(_e0) for _e0 in (self.notes or [])],
            "labels": None if self.labels is None else { _to_value(_k0): _to_value(_v0) for _k0, _v0 in (self.labels or {}).items() },
        }

@dataclass
class CreateItemRequest:
    name: ItemName
    tier: ItemTier

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CreateItemRequest":
        return cls(
            name=data.get("name"),
            tier=ItemTier.from_dict(data.get("tier")),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": _to_value(self.name),
            "tier": _to_value(self.tier),
        }

@dataclass
class ItemSummary:
    id: str
    name: ItemName

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ItemSummary":
        return cls(
            id=data.get("id"),
            name=data.get("name"),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": _to_value(self.id),
            "name": _to_value(self.name),
        }
class WebRPCError(Exception):
    name: str = "WebRPCError"
    code: int = 0
    message: str = "webrpc error"
    status: int = 400

    def __init__(self, message: Optional[str] = None, cause: Optional[str] = None):
        self.message = message if message is not None else type(self).message
        self.cause = cause
        super().__init__(self.message)

    def to_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {
            "error": self.name,
            "code": self.code,
            "msg": self.message,
            "status": self.status,
        }
        if self.cause:
            out["cause"] = self.cause
        return out


class WebrpcEndpoint(WebRPCError):
    name = "WebrpcEndpoint"
    code = 0
    message = "endpoint error"
    status = 400


class WebrpcRequestFailed(WebRPCError):
    name = "WebrpcRequestFailed"
    code = -1
    message = "request failed"
    status = 400


class WebrpcBadRoute(WebRPCError):
    name = "WebrpcBadRoute"
    code = -2
    message = "bad route"
    status = 404


class WebrpcBadMethod(WebRPCError):
    name = "WebrpcBadMethod"
    code = -3
    message = "bad method"
    status = 405


class WebrpcBadRequest(WebRPCError):
    name = "WebrpcBadRequest"
    code = -4
    message = "bad request"
    status = 400


class WebrpcBadResponse(WebRPCError):
    name = "WebrpcBadResponse"
    code = -5
    message = "bad response"
    status = 500


class WebrpcServerPanic(WebRPCError):
    name = "WebrpcServerPanic"
    code = -6
    message = "server panic"
    status = 500


class WebrpcInternalError(WebRPCError):
    name = "WebrpcInternalError"
    code = -7
    message = "internal error"
    status = 500


class WebrpcClientAborted(WebRPCError):
    name = "WebrpcClientAborted"
    code = -8
    message = "request aborted by client"
    status = 400


class WebrpcStreamLost(WebRPCError):
    name = "WebrpcStreamLost"
    code = -9
    message = "stream lost"
    status = 400


class WebrpcStreamFinished(WebRPCError):
    name = "WebrpcStreamFinished"
    code = -10
    message = "stream finished"
    status = 200


class ItemExists(WebRPCError):
    name = "ItemExists"
    code = 1
    message = "item already exists"
    status = 409


class NoSuchItem(WebRPCError):
    name = "NoSuchItem"
    code = 2
    message = "no such item"
    status = 404


class OutOfStock(WebRPCError):
    name = "OutOfStock"
    code = 3
    message = "item out of stock"
    status = 409

_errors_by_code: dict[int, type[WebRPCError]] = {
    0: WebrpcEndpoint,
    -1: WebrpcRequestFailed,
    -2: WebrpcBadRoute,
    -3: WebrpcBadMethod,
    -4: WebrpcBadRequest,
    -5: WebrpcBadResponse,
    -6: WebrpcServerPanic,
    -7: WebrpcInternalError,
    -8: WebrpcClientAborted,
    -9: WebrpcStreamLost,
    -10: WebrpcStreamFinished,
    1: ItemExists,
    2: NoSuchItem,
    3: OutOfStock,
}


def _error_from_code(code: Any, message: Optional[str] = None, cause: Optional[str] = None) -> WebRPCError:
    cls = _errors_by_code.get(code, WebRPCError)
    return cls(message=message, cause=cause)
def _to_value(v: Any) -> Any:
    if v is None:
        return None
    if isinstance(v, datetime):
        if v.tzinfo is None:
            v = v.replace(tzinfo=timezone.utc)
        return v.isoformat()
    if isinstance(v, Enum):
        return v.value
    if isinstance(v, list):
        return [_to_value(x) for x in v]
    if isinstance(v, dict):
        return {_to_value(k): _to_value(x) for k, x in v.items()}
    if hasattr(v, "to_dict"):
        return v.to_dict()
    return v


def _parse_datetime(v: Any) -> datetime:
    if isinstance(v, datetime):
        return v
    if isinstance(v, str) and v.endswith("Z"):
        v = v[:-1] + "+00:00"
    return datetime.fromisoformat(v)


def _parse_bigint(v: Any) -> int:
    # webrpc transports bigint as a decimal string; tolerate a JSON number too.
    return int(v)


def _bigint_to_value(v: Any) -> Any:
    # webrpc expects bigint on the wire as a decimal string.
    return None if v is None else str(v)


class ExampleServiceClient:
    def __init__(self, base_url: str, client: Optional["httpx.Client"] = None):
        if client is None:
            import httpx
            client = httpx.Client()
        self._base = base_url.rstrip("/") + "/v1/ExampleService/"
        self._client = client

    def get_items(self) -> list[ItemSummary]:
        _resp = self._client.post(
            self._base + "GetItems",
            json={
            },
            headers={"Content-Type": "application/json", "Accept": "application/json", "Webrpc": WEBRPC_HEADER_VALUE},
        )
        _data = self._handle_response(_resp)
        return [ItemSummary.from_dict(_e0) for _e0 in (_data.get("items") or [])]

    def get_item(self, itemId: str) -> Item:
        _resp = self._client.post(
            self._base + "GetItem",
            json={
                "itemId": _to_value(itemId),
            },
            headers={"Content-Type": "application/json", "Accept": "application/json", "Webrpc": WEBRPC_HEADER_VALUE},
        )
        _data = self._handle_response(_resp)
        return Item.from_dict(_data.get("item"))

    def create_item(self, item: CreateItemRequest) -> None:
        _resp = self._client.post(
            self._base + "CreateItem",
            json={
                "item": _to_value(item),
            },
            headers={"Content-Type": "application/json", "Accept": "application/json", "Webrpc": WEBRPC_HEADER_VALUE},
        )
        _data = self._handle_response(_resp)
        return None

    def put_one(self, itemId: str) -> None:
        _resp = self._client.post(
            self._base + "PutOne",
            json={
                "itemId": _to_value(itemId),
            },
            headers={"Content-Type": "application/json", "Accept": "application/json", "Webrpc": WEBRPC_HEADER_VALUE},
        )
        _data = self._handle_response(_resp)
        return None

    def take_one(self, itemId: str) -> None:
        _resp = self._client.post(
            self._base + "TakeOne",
            json={
                "itemId": _to_value(itemId),
            },
            headers={"Content-Type": "application/json", "Accept": "application/json", "Webrpc": WEBRPC_HEADER_VALUE},
        )
        _data = self._handle_response(_resp)
        return None

    def delete_item(self, itemId: str) -> None:
        _resp = self._client.post(
            self._base + "DeleteItem",
            json={
                "itemId": _to_value(itemId),
            },
            headers={"Content-Type": "application/json", "Accept": "application/json", "Webrpc": WEBRPC_HEADER_VALUE},
        )
        _data = self._handle_response(_resp)
        return None

    def count_by_tier(self) -> dict[ItemTier, int]:
        _resp = self._client.post(
            self._base + "CountByTier",
            json={
            },
            headers={"Content-Type": "application/json", "Accept": "application/json", "Webrpc": WEBRPC_HEADER_VALUE},
        )
        _data = self._handle_response(_resp)
        return { ItemTier.from_dict(_k0):_v0 for _k0, _v0 in (_data.get("counts") or {}).items() }

    def _handle_response(self, resp: "httpx.Response") -> dict[str, Any]:
        if resp.status_code >= 400:
            try:
                body = resp.json()
            except Exception:
                raise WebRPCError(message="invalid response from server")
            raise _error_from_code(body.get("code"), body.get("msg"), body.get("cause"))
        if not resp.content:
            return {}
        return resp.json()


class ExampleService(Protocol):
    def get_items(self) -> list[ItemSummary]:
        ...
    def get_item(self, itemId: str) -> Item:
        ...
    def create_item(self, item: CreateItemRequest) -> None:
        ...
    def put_one(self, itemId: str) -> None:
        ...
    def take_one(self, itemId: str) -> None:
        ...
    def delete_item(self, itemId: str) -> None:
        ...
    def count_by_tier(self) -> dict[ItemTier, int]:
        ...


class ExampleServiceServer:
    """Framework-agnostic WSGI application that serves a ExampleService implementation."""

    def __init__(self, service: "ExampleService"):
        self._service = service
        self._routes = {
            "/v1/ExampleService/GetItems": self._get_items,
            "/v1/ExampleService/GetItem": self._get_item,
            "/v1/ExampleService/CreateItem": self._create_item,
            "/v1/ExampleService/PutOne": self._put_one,
            "/v1/ExampleService/TakeOne": self._take_one,
            "/v1/ExampleService/DeleteItem": self._delete_item,
            "/v1/ExampleService/CountByTier": self._count_by_tier,
        }

    def __call__(self, environ, start_response):
        if environ.get("REQUEST_METHOD") != "POST":
            return self._error(start_response, WebrpcBadMethod(), [("Allow", "POST")])
        handler = self._routes.get(environ.get("PATH_INFO", ""))
        if handler is None:
            return self._error(start_response, WebrpcBadRoute())
        content_type = environ.get("CONTENT_TYPE", "").split(";")[0].strip().lower()
        if content_type != "application/json":
            return self._error(start_response, WebrpcBadRequest(message="Content-Type must be application/json"))
        try:
            length = int(environ.get("CONTENT_LENGTH") or 0)
        except (TypeError, ValueError):
            return self._error(start_response, WebrpcBadRequest(message="invalid Content-Length"))
        raw = environ["wsgi.input"].read(length) if length else b""
        try:
            data = json.loads(raw) if raw else {}
        except (json.JSONDecodeError, UnicodeDecodeError):
            return self._error(start_response, WebrpcBadRequest(message="invalid JSON body"))
        if not isinstance(data, dict):
            return self._error(start_response, WebrpcBadRequest(message="request body must be a JSON object"))
        try:
            return self._respond(start_response, 200, handler(data))
        except WebRPCError as err:
            return self._error(start_response, err)
        except Exception as err:
            return self._error(start_response, WebrpcServerPanic(cause=str(err)))

    def _headers(self, body: bytes):
        return [
            ("Content-Type", "application/json"),
            ("Content-Length", str(len(body))),
            ("Webrpc", WEBRPC_HEADER_VALUE),
        ]

    def _respond(self, start_response, status: int, payload: dict[str, Any]):
        body = json.dumps(payload).encode("utf-8")
        start_response(f"{status} ", self._headers(body))
        return [body]

    def _error(self, start_response, err: "WebRPCError", extra_headers=None):
        body = json.dumps(err.to_dict()).encode("utf-8")
        headers = self._headers(body)
        if extra_headers:
            headers.extend(extra_headers)
        start_response(f"{err.status} ", headers)
        return [body]

    def _get_items(self, data: dict[str, Any]) -> dict[str, Any]:
        result = self._service.get_items(
        )
        return {"items": [_to_value(_e0) for _e0 in (result or [])]}

    def _get_item(self, data: dict[str, Any]) -> dict[str, Any]:
        result = self._service.get_item(
            itemId=data.get("itemId"),
        )
        return {"item": _to_value(result)}

    def _create_item(self, data: dict[str, Any]) -> dict[str, Any]:
        result = self._service.create_item(
            item=CreateItemRequest.from_dict(data.get("item")),
        )
        return {}

    def _put_one(self, data: dict[str, Any]) -> dict[str, Any]:
        result = self._service.put_one(
            itemId=data.get("itemId"),
        )
        return {}

    def _take_one(self, data: dict[str, Any]) -> dict[str, Any]:
        result = self._service.take_one(
            itemId=data.get("itemId"),
        )
        return {}

    def _delete_item(self, data: dict[str, Any]) -> dict[str, Any]:
        result = self._service.delete_item(
            itemId=data.get("itemId"),
        )
        return {}

    def _count_by_tier(self, data: dict[str, Any]) -> dict[str, Any]:
        result = self._service.count_by_tier(
        )
        return {"counts": { _to_value(_k0): _to_value(_v0) for _k0, _v0 in (result or {}).items() }}